# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:git

services:
  - docker:dind

before_script:
  # Install dependencies
  - apk add --no-cache curl jq
  # Login to docker hub
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  # Get the latest successful pipeline commit
  # More info: https://gitlab.com/gitlab-org/gitlab-ce/issues/19813
  - >
    export LAST_COMMIT=$(curl --header "PRIVATE-TOKEN: $CI_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines" |
    jq -r '.[1].sha')

stages:
  - minimal
  - basic
  - custom
  - tools
  - adntools
  - adnamc

build:minimal:
  stage: minimal
  variables:
    IMAGE_TAG: "minimal"
  script:
    - ./build.sh
  artifacts:
    paths:
      - variables

build:basic:
  stage: basic
  variables:
    IMAGE_TAG: "basic"
  script:
    - source ./variables
    - ./build.sh
  artifacts:
    paths:
      - variables
  dependencies:
    - build:minimal

build:custom:
  stage: custom
  variables:
    IMAGE_TAG: "custom"
  script:
    - source ./variables
    - ./build.sh
  dependencies:
    - build:minimal

build:tools:
  stage: tools
  variables:
    IMAGE_TAG: "tools"
  script:
    - source ./variables
    - ./build.sh
  dependencies:
    - build:custom

build:adntools:
  stage: adntools
  variables:
    IMAGE_TAG: "adntools"
  script:
    - source ./variables
    - ./build.sh
  dependencies:
    - build:tools

build:adnamc:
  stage: adnamc
  variables:
    IMAGE_TAG: "adnamc"
  script:
    - source ./variables
    - ./build.sh
  dependencies:
    - build:adntools
